version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: '/client'
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: '/server'
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
